"""empty message

Revision ID: 90d38a83fd23
Revises: a5cffa318ac2
Create Date: 2026-01-28 15:03:48.349576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d38a83fd23'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lugar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaje_simpson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('ocupacion', sa.String(length=120), nullable=True),
    sa.Column('frase_iconica', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito_simpson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.Column('lugar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugar.id'], ),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje_simpson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito_simpson')
    op.drop_table('personaje_simpson')
    op.drop_table('lugar')
    # ### end Alembic commands ###
